### ISSUE TITLE
Why do they sterilize needles for lethal injections?

### ISSUE THREAD

**Issue by seanc** [jamen/ama#78]

**Comment by jamen** [comment]
I couldn't tell you for sure, but it seems pretty trivial.  

My guess is for policy, as I believe death row people are treated well in their last few days.  There is probably also some documented procedure that has to be followed.  Other possibilities I could think of is contaminating the injection (how do you get a reliable source of unsterile needles guaranteed to work?), or contaminating the body if they are an organ donor.

Regardless, it appears that sterilization is cost-ineffective, as it just requires some long exposure to pressure and steam.  Professionally, these things called [autoclaves](https://en.wikipedia.org/wiki/Autoclave) are used.

**Comment by jamen** [comment]
It also appears there is a legal aspect.  If the needle was inside your right before you got a call from the judge that the case was turned around, if you got an infection from that unsterile needle you could sue the government.  So, might as well do it.
